service: menu-app-serverless-api

plugins:
  - serverless-esbuild
  - serverless-domain-manager
  - serverless-offline

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1

functions:
  healthCheck:
    handler: src/health-check/handler.healthCheck
    events:
      - httpApi:
          path: /health
          method: get
  version:
    handler: src/version/handler.version
    events:
      - httpApi:
          path: /
          method: get


custom:
  esbuild:
    watch:
      pattern: ['src/**/*.ts']

  customDomain:
    domainName: api.menu-app.em-dev.org
    stage: dev
    certificateName: '*.menu-app.em-dev.org'
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: http
    autoDomain: false
